### ISSUE TITLE
Allow for absolute path for input specification + better info for parameters

### ISSUE THREAD

**Issue by RiccardoRomanello** [eth-sri/synthetiq#1]
Hello, 

this afternoon I have downloaded synthetiq on a Intel Mac using Docker. 
The 'test' line: ./bin/main cx.txt works properly. 
However, I read in the README that such command actually inputs data/input/cx.txt to the main file. 
Therefore, I tried to prompt the following command in the terminal: ./bin/main input/data/cx.txt

What I obtain as output is the following: 

```
Input file: input/data/cx.txt
Output folder: input/data/cx/
Format: txt
Gate set: CliffordT
Composite gate folder: composite_gates
Number of threads: 1
Number of circuits to find: 10
Number of ancillas: 0
Number of dirty qubits: 0
Optimal t-count: -1
Optimal t-depth: -1
Optimal gate count: -1
Cost required: -1
Time allowed: 100
Start temp base: 0.1
Epsilon: 1e-06
Beta: 0.05
Min factor: 2.5
Max factor: 3.5
Pcomp: 0.2
Pid: 0.3
Enable permutations: 1
Do resynth: 1
Simple cost: 0
N norm: 80
Iterations factor: 40
Update gate scheme: 1
Save times: 0
Expand composite: 0
Qubit independent: 1
Save all circuits: 0
Save any circuit: 1
Times file: data/times.csv
Optimization number: 12
Optimize depth: 1
Inverse independent: 0
Depth gates: t tdg 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

The same happens for any input file (different from cx.txt) that I provide. 
Am I wrongly using the tool?

Best, 
Riccardo

**Comment by JasperDekoninck** [comment]
Hi Riccardo!

The tool automatically inserts "data/input" in front of the input file location you provide. Therefore, if your run "./bin/main input/data/cx.txt", Synthetiq will look for the file "data/input/input/data/cx.txt". Thus, to use the tool, you should place any of your input files in the "data/input" folder and run Synthetiq with input file specified relative to this input folder. To make the command " ./bin/main input/data/cx.txt" work, you should create a subfolder "input/data" in the "data/input" folder and put the cx.txt file there.

If you want to change this behavior, you would need to change line 17 in `synthetic/algo.h` to the base input folder where you want to store your input files.

Hope this helps :)

**Comment by RiccardoRomanello** [comment]
Thanks a lot, 
now it works property!

I do not know if you already thought about it, but in the 'metainfos' you print when the main is launched, there is the 'Input file' dedicated row. 
I would suggest printing the absolute path after this append. 

Best, 
Riccardo

**Comment by JasperDekoninck** [comment]
Yeah, you are not the first to be confused about the relative path used, I think I will do both your suggestion and also allow for absolute path specification.

**Comment by JasperDekoninck** [comment]
That should do the trick :)
The logging information now specified the absolute path instead of the relative path for both input file, output folder and gate folders.
You can additionally specify an absolute path instead of a relative path by specifying your absolute path and activating one of the following parameters:
- --absolute-input: boolean indicating that the input path is absolute
- --absolute-output: boolean indicating that the output path is absolute
- --absolute-gates: boolean indicating that the gates path is absolute

So, for instance, the example in the README, `./bin/main cx.txt`, can equivalently be run as:
`./bin/main data/input/cx.txt --output data/output/cx --absolute-input --absolute-output`

**Comment by RiccardoRomanello** [comment]
Thanks a lot, 

that was super fast!

Riccardo
